### ISSUE TITLE
JavaScript Time error

### ISSUE THREAD

**Issue by ryanwhowe** [ryanwhowe/statusboard#27]
**Describe the bug**
 When you view the page after 10 hours has passed from the arrival time the page will air out with JavaScript error.

**To Reproduce**
 This is a little hard to reproduce because of the minimums that are set on the page but you need to view the page with the arrival time set to more than 10 hours in the past.

**Expected behavior**
 I expect the page to be viewable in dimmable at anytime of the day or night without any JavaScript errors.

**Comment by rhowe-ds** [comment]
The 10 hour calculation might be better served to be something along the lines of 10 hours or (currentHour - startHour)+5 whichever is higher.

**Comment by ryanwhowe** [comment]
Resolved in PR #38
