### ISSUE TITLE
Update Payday Schedule

### ISSUE THREAD

**Issue by rhowe-ds** [ryanwhowe/statusboard#29]
**Describe the bug**
The new payroll schedule is a 24 pay period schedule with payments on the 15th and last day of the month.

The system is still set up to be every even Friday of the year.

**Expected behavior**
That the payday schedule is on the 15th and last day of the month.

**Comment by rhowe-ds** [comment]
Test function to adjust pay date based on weekends
http://sandbox.onlinephpfunctions.com/code/a75179eece22a36a4df419bb0eed45b52589f385

**Comment by ryanwhowe** [comment]
Resolved in pr #30
