### ISSUE TITLE
Working Days in Month

### ISSUE THREAD

**Issue by rhowe-ds** [ryanwhowe/statusboard#36]
**Is your feature request related to a problem? Please describe.**
There is already a calculator implemented for this as part of the Clock class to determine the days left in the month and percent of month remaining.  This calculation would be useful also for determining if a monthly MBTA pass would be worth purchasing since I commute right on the edge of the number of days that would make this purchase worth it.

**Describe the solution you'd like**
I would like to be able to see the amount of working days in a given month.  I do not have a specific UI implementation in mind.  But the year/month should be user selectable in some way.

**Describe alternatives you've considered**
The only alternative that I could think of would be hand calculations.

**Additional context**
If there is an API anywhere that says the price of the current/next month MBTA pass for zone 6 it would be nice to calculate the days needed to break even using the pass vs straight tickets.

**Comment by ryanwhowe** [comment]
Now that #41 has been completed this data should be used as well when determining working days in the month.

**Comment by ryanwhowe** [comment]
Along with that, #41 has made available the holidays and work holidays that are in the month.  However there still needs to be an actual end result for a solution to be proposed.  Be it an api end point that returns data OR some ideas for a UI display with what information would be helpful.

Also the MBTA has changed their pricing structure once again and it looks like they have adopted a fixed cost of $330.00 per month for a pass so there is no need to try and add additional data pulls for the zone 6 pass prices.

**Comment by ryanwhowe** [comment]
I am going to close out this issue.  I have tried to come up with a reasonable UI design and the utility of this addition as been more and more reduced since the commuting has been reduced to 0 due to Covid-19
