### ISSUE TITLE
Add todays weather widget

### ISSUE THREAD

**Issue by rhowe-ds** [ryanwhowe/statusboard#37]
**Is your feature request related to a problem? Please describe.**
I always check the WeatherUnderground 10 day forecast for todays forecast.  

**Describe the solution you'd like**
I would like a WeatherUnderground integrated widget available on the dashboard with the ability to configure at least the postal code.

**Describe alternatives you've considered**
There may be something that is already provided by WU that could perform the functionality that I am looking for.  I have done no research into the integration options that they provide.

**Comment by ryanwhowe** [comment]
Got a personal development key for Accuweather, had to set a "go live" date for the application, soo come December 31, 2022 it will be interesting to see what happens to the API key
